### PR TITLE
Doc corrections

### PR DESCRIPTION
**Pull request by keflavich**
I'm making a few small language corrections as I go.  For bigger issues or suggested changes, I'll submit independent github issues.  This is a WIP; I'll mark it done when I've read everything.

### CODE REVIEW

**Comment by keflavich** [comment]
A general point: consider changing the plot style.  The big diamond points are too big in most cases and obscure the data.

**Comment by keflavich** [comment]
Another general point: the fitted lines in power spectra and some other models are the same color as the data, which renders them invisible.  The fits should be a different color.

**Comment by keflavich** [comment]
MVC and pspec include some redundant text; maybe it's best to just refer to pspec in mvc?

**Comment by e-koch** [comment]
Thanks! I'm going to use this PR to address everyone else's small comments, too.

Just a travis failure. Or something to do with the numpy prerelease. I'm seeing the same failure for other packages, too.

**Comment by e-koch** [comment]
Most of Ryan and Stella, and Blakesley's comments are now included.

**Comment by e-koch** [comment]
NOTE: The spectral downsampling for the VCA requires `SpectralCube.downsample_axis`.

* [ ] - Require spectral-cube >=v0.4.4 (probably need a new spectral-cube release)

**Comment by keflavich** [comment]
We can tag a new release any time you like.

**Comment by e-koch** [comment]
Changed the defaults in delta-variance to *not* interpolate over NaNs by default. I was getting bad edge effects in the delta-variance when NaNs were interpolated over at the edges of masked regions.

**Comment by e-koch** [comment]
List of major changes to the docs:

* Page on how to contribute
* Added everyone to the list of developers
* Page describing data used in the tutorials
* Added tutorial comparing the effects of masking and noise. Examples using the power-spectrum and delta-variance. Recommends users compare their data w/ and w/o masking for the statistics they are using. The tutorial also lists the common effects on noise
* Default plotting style uses red circle with a black line overplotted for fits.

**Pull request merged**
